[project]
name = "personal-finance-etl"
version = "0.1.0"
description = "E2E ETL App for processing my personal finances and investment data for robust investment and tax capabilities"
authors = [
  { name="Shan", email="tksudharshan@gmail.com" },
]
license = "GPL-3.0-only"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adbc-driver-sqlite>=1.11.0",
    "customtkinter>=6.0.0",
    "fastexcel>=0.20.2",
    "pillow>=12.3.0",
    "polars>=1.42.1",
    "pyarrow>=25.0.0",
    "python-dateutil>=2.9.0.post0",
    "pyxirr>=0.10.8",
    "tkcalendar>=1.6.1",
    "yfinance>=1.5.1",
]

[dependency-groups]
dev = [
    "poethepoet>=0.48.0",
    "pyinstaller>=6.21.0",
    "tkreload>=1.0.4",
]

[tool.poe.tasks]
dev = "uv run python -c 'from scripts.tasks import dev; dev()'"
build = "uv run python -c 'from scripts.tasks import build; build()'"

[tool.uv]
package = true

[tool.uv.sources]
tasks = { path = "./scripts/tasks.py" }

[project.urls]
Homepage = "https://github.com/tks18/personal-finance-etl"
Documentation = "https://github.com/tks18/personal-finance-etl#readme"
Repository = "https://github.com/tks18/personal-finance-etl"
Issues = "https://github.com/tks18/personal-finance-etl/issues"
Changelog = "https://github.com/tks18/personal-finance-etl/releases"
